### ISSUE TITLE
Speedup pushing frames throughout caffe

### ISSUE THREAD

**Issue by adithyamurali** [BerkeleyAutomation/tsc-dl#4]
Discovered that main problem is on line 327 in `utils.py`

```
    if key not in data_dict:
        data_dict[key] = value
    else:
        curr_value = data_dict[key]
        curr_value = np.concatenate((curr_value, value), axis = axis) #issue
        data_dict[key] = curr_value
```

Array is newly allocated every time something is concatenated. Therefore, there needs to be a way to avoid this O(n^2) operation
### Idea
1. Allocate all memory with `np.zeros` initially
2. Update rows until filled
3. Write out to disk
- [ ] Spilling intermediate steps to disk to avoid memory overflow
- [ ] Making sure data can be recovered back to previous format

**Comment by richardliaw** [comment]
### Discussion regarding memory mapping to deal with large files:

http://stackoverflow.com/questions/13780907/is-it-possible-to-np-concatenate-memory-mapped-files

### Discussion regarding memory usage:

http://stackoverflow.com/questions/938733/total-memory-used-by-python-process

**Comment by richardliaw** [comment]
b1baa409c81e12651adbc25d4c8f7851a31fdb5b has changed some code to allow very fast concatenation.
